SUBJECT: Error in IQAMA_JOB_AHJ_DOT-CARE on AHQ-AI-02
TIME: 2025-04-30 16:01:03
HOST: AHQ-AI-02
SYSTEM: Windows 2019Server
PYTHON: 3.12.8

==================================================

An error occurred in the IQAMA_JOB_AHJ_DOT-CARE job on AHQ-AI-02 at 2025-04-30 16:01:03.

Error details:
cannot access local variable 'timestamp' where it is not associated with a value

Traceback (most recent call last):
  File "C:\Data-Science\Deployment\Eligibilty_api_schedule\eligibilty_api_schedule.py", line 60, in _eligibility_iqama_job
    df_new.to_csv(f"iqama_data/in/IN_DATA_{timestamp}.csv")
                                           ^^^^^^^^^
UnboundLocalError: cannot access local variable 'timestamp' where it is not associated with a value


Please check the scheduler.log file for more information.